### ISSUE TITLE
python hangs after failed 'onecmd'

### ISSUE THREAD

**Issue by kadrlica** [mgckind/easyaccess#106]
My python session hangs when using the API for an unsuccessful call to `onecmd`:
```
>>> import easyaccess as ea
>>> con = ea.connect()
>>> con.onecmd('select * from NOT_A_TABLE;')

<class 'cx_Oracle.DatabaseError'>
ORA-00942: table or view does not exist

>>> exit()
# Python session hangs hear and cannot exit with
# ^D, ^C, or ^Z
```
This is interesting because a direct call to `con.cursor().execute` does not cause this behavior:
```
>>> import easyaccess as ea
>>> con = ea.connect()
>>> con.cursor().execute('select * from NOT_A_TABLE;')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cx_Oracle.DatabaseError: ORA-00911: invalid character
>>> exit()
```
Maybe I shouldn't be using `onecmd`? If this is the case, then we should document the proper interface for calling functions as if from the interactive command line.

**Comment by mgckind** [comment]
It fails because it doesn't catch the exception raised by `exit` when there is a subpreocess. That's the reason to use os._exit(0) after all the onecmd in the code (there are several at the bottom), It kind of wait for a returned before exit, while os.exit(0) just send the kill signal.

In general it works but given the forked processed (using `threading`) sys.exit(0) hangs. 
http://stackoverflow.com/questions/9591350/what-is-difference-between-sys-exit0-and-os-exit0
 http://stackoverflow.com/questions/905189/why-does-sys-exit-not-exit-when-called-inside-a-thread-in-python

onecmd is for internal purposes only,  If there is a specific command it can be added, there are several functions implemented and you can also access them calling directly with `do_`.

**Comment by kadrlica** [comment]
If `onecmd` is for internal use, maybe it should be `_onecmd`?

**Comment by mgckind** [comment]
it comes from `Cmd` module really, and it can be used for other commands, it is just the `default` methods has a threading process that when it fails it hangs at exit normally, that's all. Maybe there is a way to fix that default method if this is a common problem. `cursor.execute()` and `query_to_pandas()` are the best depending on what's needed.
