### ISSUE TITLE
Argument groups

### ISSUE THREAD

**Issue by kadrlica** [mgckind/easyaccess#28]
I think we are inexorably moving towards having more and more command line options. I would like to refactor the argparser to use argument groups. My current vision is to split the argparser into a separate file (eaparser.py) to avoid cluttering the main code. This brings up the larger topic that easyaccess.py is getting quite long (>2000 lines). Is this intentional?

Feel free to assign this to me.

**Comment by mgckind** [comment]
It's a nice coincidence you bring this up. I just added an optional argument (username and password) and I thought about grouping them. I guess there are other priorities as well and its nice that its being used. At some point is more on user taste and general request on which we should focus on. Anyways, as we keep adding option we can think about grouping them and remove some of the code from the main file.

And yes, it was intentional to have just one large file because at some point we thought (and it was done with trivialAccess) to have the whole code as a BLOB in the DB so you can update changes (as it was done in trivialaccess) from inside, in an self-consistent way.  In that case, a select would bring the BLOB and replace your current version which was in one file.

Since we are using eups/pip this might not longer the case, I just need to find time to reorganize it... :0

**Comment by kadrlica** [comment]
Ok, I don't understand the BLOB model, so just tell me if/when it is ok to start splitting the code into subfiles.

**Comment by mgckind** [comment]
I'm closing this issue since it can't be addressed directly but we know it might happen soon related to put the argparse in a separate file.
