### ISSUE TITLE
Access to Postgres Databases

### ISSUE THREAD

**Issue by kadrlica** [mgckind/easyaccess#29]
I realize this is a huge one, but I figured I'd put it up here anyway (and I'm definitely willing to contribute)...

Would it be possible to write an intermediate layer between the API and the DB access which will allow easyaccess to interface with both the Oracle and Postgres databases used by DES? My suggestion would be to learn from [despydb](https://dessvn.cosmology.illinois.edu/websvn/desdm/devel/despydb/trunk/python/), but not to duplicate that code exactly. Since the desservices.ini file already contains the necessary credentials to access both databases, the user interface should not need to change.

**Comment by mgckind** [comment]
It might be a huge one,  I though about using sqlalchemy instead of cx_Oracle to have a more general interface with the DB. Then since most (all) of users will access mainly the Oracle DB I went for cx_Oracle. I guess you can add "easily"  more functionalities for Postgres to the python easyaccess API, but then the interactive part might be the complex one to adapt.

**Comment by kadrlica** [comment]
If you have a few seconds, take a look at what was done in despydb. Whoever designed that code already thought about some subsection of the stumbling blocks. I don't think we should ever think that we'll allow users access in a completely DB independent manner, but it would be nice to at least allow the advanced user a way to access the telemetry and other operations databases.

**Comment by mgckind** [comment]
There is this general idea of me trying to change to SLQAlchemy, which might solve this issue. I'm closing this but if you think we need to address this issue feel free to re-open. :)
